openapi: 3.0.0
info:
  title: Rep Finances API
  description: Tool for register transactions among a group of people and calculate the finances balance in the group.
  version: 1.2.1-alpha
servers:
  - url: 'http://repsy-api.herokuapp.com/api'
    description: Production server
  - url: 'http://localhost:3333/api'
    description: Internal server
components:
  schemas:
    TransactionItems:
      type: object
      additionalProperties:
        type: object
        properties:
          amount:
            type: number
          related_users:
            type: array
            items:
              type: string
      example:
        Brown sugar:
          amount: 15
          related_users:
            - P
            - FB
        Cat sand:
          amount: 15
          related_users:
            - FB
    TransactionPayers:
      type: object
      additionalProperties:
        type: number
      example:
        P: 10
        FB: 20
    Transaction:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        date:
          type: string
          format: Date
        items:
          $ref: '#/components/schemas/TransactionItems'
        payers:
          $ref: '#/components/schemas/TransactionPayers'
        month:
          type: string
        amount:
          type: number
        related:
          type: array
          items:
            type: string
      example:
        _id: 96986f8d-720d-4ddd-a933-0570d82e71af
        title: 100h cookie recipe
        date: 2021-04-17T13:30:00.000Z
        items:
          Brown sugar:
            amount: 15
            related_users:
              - P
              - FB
          Cat sand:
            amount: 15
            related_users:
              - FB
        payers:
          P: 10
          FB: 20
        month: 202104
        amount: 30
        related:
          - P
          - FB
    Balance:
      type: object
      additionalProperties:
        type: number
      example:
        P: 2.5
        FB: -2.5
  responses:
    InvalidFields:
      description: The data is invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                    field:
                      type: string
                  required:
                    - message
            required:
              - name
              - errors
            example:
              name: InvalidFieldsError
              errors:
                - message: 'The id cannot contain special characters, nor can it contain a number in the first position.'
                  field: items.item1.related_users.__
                - message: The amount must be a positive number.
                  field: payers.P.amount
    InvalidInput:
      description: The given data does not match with the expected
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                    field:
                      type: string
                  required:
                    - message
            required:
              - name
              - errors
            example:
              name: InvalidInputError
              errors:
                - message: 'Invalid input: title is a required field'
                  field: title
                - message: 'Invalid input: timestamp must be a `number` type, but the final value was: `NaN` (cast from the value `"abacate"`).'
                  field: timestamp
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                    field:
                      type: string
                  required:
                    - message
            required:
              - name
              - errors
            example:
              name: TransactionNotFoundError
              errors:
                - message: There is no transaction registered with _id "id-123"
                  field: _id
    Server:
      description: An unexpected condition was encountered
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
                    field:
                      type: string
                  required:
                    - message
            required:
              - name
              - errors
            example:
              name: ServerError
              errors:
                - message: 'Server error: Unexpected error'
paths:
  /transactions:
    get:
      tags:
        - Finances
      summary: Returns a list of registered transactions
      description: 'Returns a list of registered transactions paginated by the "page" query (positive number, defaults to 1) and "nItems" query (positive number, defaults to 15)'
      operationId: listTransactions
      parameters:
        - name: page
          in: query
          description: 'Page number (positive number, defaults to 1)'
          schema:
            type: integer
            minimum: 1
        - name: nItems
          in: query
          description: 'Number of items per page (positive number, defaults to 15)'
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: A JSON array of transaction resumes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    title:
                      type: string
                    date:
                      type: string
                      format: Date
                    amount:
                      type: number
                    related:
                      type: array
                      items:
                        type: string
                  example:
                    _id: 96986f8d-720d-4ddd-a933-0570d82e71af
                    title: 100h cookie recipe
                    date: 2021-04-17T13:30:00.000Z
                    amount: 30
                    related:
                      - P
                      - FB
        '400':
          $ref: '#/components/responses/InvalidInput'
        '500':
          $ref: '#/components/responses/Server'
    post:
      tags:
        - Finances
      summary: Register a new transaction in the repository
      description: Register a new transaction in the repository and set the month balance to not updated
      operationId: createTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                timestamp:
                  type: number
                items:
                  $ref: '#/components/schemas/TransactionItems'
                payers:
                  $ref: '#/components/schemas/TransactionPayers'
              example:
                title: 100h cookie recipe
                timestamp: 1618666200000
                items:
                  Brown sugar:
                    amount: 15
                    related_users:
                      - P
                      - FB
                  Cat sand:
                    amount: 15
                    related_users:
                      - FB
                payers:
                  P: 10
                  FB: 20
      responses:
        '201':
          description: 'Created, returns the created transaction'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/InvalidInput'
        '406':
          $ref: '#/components/responses/InvalidFields'
        '500':
          $ref: '#/components/responses/Server'
  /transactions/count:
    get:
      tags:
        - Finances
      summary: Returns the number of registered transactions
      description: Returns the number of registered transactions
      operationId: getTransactionsCount
      responses:
        '200':
          description: Transactions count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    example: 15
        '500':
          $ref: '#/components/responses/Server'
  '/transactions/{id}':
    get:
      tags:
        - Finances
      summary: Recover a registered transaction by id
      description: Returns all props of the registered transaction with given id and its balance
      operationId: getTransactionById
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An object with the transaction props and balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction:
                    $ref: '#/components/schemas/Transaction'
                  balance:
                    $ref: '#/components/schemas/Balance'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/Server'
  /balance:
    get:
      tags:
        - Finances
      summary: Returns the current balance
      description: Returns the most updated balance including all registered transactions
      operationId: getBalance
      responses:
        '200':
          description: Current balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    $ref: '#/components/schemas/Balance'
        '500':
          $ref: '#/components/responses/Server'
